theme = 'kanagawa'

[editor]
scrolloff = 3
line-number = 'relative'
shell = ['zsh', '-c']
cursorline = true
true-color = true
rulers = [80]
bufferline = 'multiple'
color-modes = true
text-width = 100

[editor.statusline]
left = ['mode', 'spinner', 'position', 'selections', 'total-line-numbers']
center = ['file-name', 'file-modification-indicator', 'version-control']
right = ['diagnostics', 'file-type', 'file-line-ending', 'file-encoding']
mode.normal = 'NORMAL'
mode.insert = 'INSERT'
mode.select = 'SELECT'

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.file-picker]
hidden = false
git-ignore = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
'<' = '>'

[editor.whitespace.render]
nbsp = 'all'
tab = 'all'

# KEYS --------------------------------
[keys.normal]
'ret' = ['open_below', 'normal_mode']
'tab' = ':buffer-next'

[keys.insert]
k = { k = "normal_mode" }

[keys.normal.'space']
'space' = 'command_mode'
l = ':reflow 80'
u = ':update'

# Buffers
[keys.normal.'space'.b]
b = 'buffer_picker'
n = ':new'
c = ':buffer-close'
o = ':buffer-close-others'
O = ':buffer-close-others!'

# Quits
[keys.normal.'space'.q]
q = ':quit'
Q = ':quit-all'
f = ':quit!'
F = ':quit-all!'
W = ':write-quit-all'
