theme = 'rose_pine'

[editor]
shell = ['zsh', '-c']
line-number = 'relative'
cursorline = true
true-color = true
color-modes = true
undercurl = true
rulers = [80]
text-width = 100
bufferline = 'multiple'
smart-tab.enable = true
mouse = true
scrolloff = 0

[editor.statusline]
left = ['mode', 'spinner', 'position', 'selections', 'total-line-numbers']
center = ['file-name', 'file-modification-indicator', 'version-control']
right = ['diagnostics', 'file-type', 'file-line-ending', 'file-encoding']
mode.normal = 'NORMAL'
mode.insert = 'INSERT'
mode.select = 'SELECT'

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.file-picker]
hidden = false
ignore = true
git-global = true
git-ignore = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
'<' = '>'

[editor.whitespace.render]
nbsp = 'all'
tab = 'all'
space = 'all'

[editor.whitespace.characters]
space = '·'
nbsp = '⍽'
tab = '│'
newline = '⏎'
# tabpad = '→'

# KEYS --------------------------------
[keys.normal]
'ret' = ['open_below', 'normal_mode']
'tab' = ':buffer-next'
'S-tab' = ':buffer-previous'
up = ['move_line_up', 'align_view_center']
down = ['move_line_down', 'align_view_center']
k = 'scroll_up'
j = 'scroll_down'
esc = ['collapse_selection', 'keep_primary_selection']
S-down = ['ensure_selections_forward', 'extend_to_line_bounds',
  'extend_char_right', 'extend_char_left', 'delete_selection',
  'add_newline_below', 'move_line_down', 'replace_with_yanked']
S-up = ['ensure_selections_forward', 'extend_to_line_bounds',
  'extend_char_right', 'extend_char_left', 'delete_selection', 'move_line_up',
  'add_newline_above', 'move_line_up', 'replace_with_yanked']

[keys.select]
esc = ['collapse_selection', 'normal_mode']

[keys.insert]
k = { k = 'normal_mode' }

[keys.normal.'space']
'space' = 'command_mode'
l = ':reflow 80'
u = ':update'
o = 'file_picker_in_current_buffer_directory'

# Buffers
[keys.normal.'space'.b]
b = 'buffer_picker'
n = ':new'
c = ':buffer-close'
C = ':buffer-close!'
o = ':buffer-close-others'
O = ':buffer-close-others!'

# Quits
[keys.normal.'space'.q]
q = ':quit'
Q = ':quit-all'
f = ':quit!'
F = ':quit-all!'
W = ':write-quit-all'

# Config
[keys.normal.'space'.c]
c = ':config-open'
l = ':o ~/.config/helix/languages.toml'
r = ':config-reload'
h = ':set lsp.display-inlay-hints true'
H = ':set lsp.display-inlay-hints false'
