[[language]]
name = 'go'
auto-format = true
formatter = { command = 'goimports' }
indent = { tab-width = 3, unit = '\t' }

[[language]]
name = 'sql'
language-servers = [ 'sql-language-server' ]
indent = { tab-width = 3, unit = '\t' }

[language-server.sql-language-server]
command = 'sql-language-server'
args = ['up', '--method', 'stdio']

[[language]]
name = 'python'
language-servers = [ 'pyright', 'ruff' ]
indent = { tab-width = 3, unit = '\t' }

[language-server.pyright.config.python.analysis]
typeCheckingMode = 'basic'

[language-server.ruff]
command = 'ruff-lsp'

[language-server.ruff.config.settings]
args = ['--ignore', 'E501']

[language.formatter]
command = 'black'
args = ['--line-length', '88', '--quiet', '-']

[[language]]
name = 'lua'
indent = { tab-width = 3, unit = '\t' }

[[language]]
name = 'html'
language-servers = [ 'tailwindcss-ls', 'vscode-html-language-server' ]

[[language]]
name = 'javascript'
indent = { tab-width = 3, unit = '\t' }

[[language]]
name = 'typescript'
indent = { tab-width = 3, unit = '\t' }

[[language]]
name = 'json'
language-servers = ['vscode-json', 'typescript-language-server']

[[language]]
name = 'svelte'
language-servers = [ 'svelteserver', 'tailwindcss-ls' ]
roots = ['svelte.config.js']
indent = { tab-width = 3, unit = '\t' }

[language-server.vscode-json]
command = 'vscode-json-language-server'
args = ['--stdio']

[[language]]
name = 'toml'
formatter = { command = 'taplo', args = ['fmt', '-'] }
indent = { tab-width = 3, unit = '\t' }

# [[language]]
# name = 'nix'
# formatter = { command = 'nixpkgs-fmt' }
